batch_size: 256
num_devices: 1
momentum_base: 0.996
momentum_max: 1.0
momentum_increase: true
dataset: cifar20
eval_metric:
  - nmi
  - acc
  - ari
whole_dataset: true
encoder_name: bigresnet18
epochs: 1000
feat_dim: 256
hidden_size: 4096
img_size: 32
lambda_predictor_lr: 10
learning_rate: 0.05
learning_eta_min: 0.
reassign: 1
save_freq: 200
save_checkpoints: true
shuffling_bn: true
symmetric: true
temperature: 0.5
use_gaussian_blur: false
warmup_epochs: 50
weight_decay: 0.0005
dist: true
data_resample: true
v2: false

model_name: propos
cluster_loss_weight: 0.05
latent_std: 0.001

wandb: false
project_name: 'hadis_cifar20_bs256'
entity: 'reganzhang'
